#!/bin/bash

# Define icons
export CHECK_ICON="${COLOR_GREEN}✔${RESET_COLOR}"
export ERROR_ICON="${COLOR_RED}✖${RESET_COLOR}"
export INFO_ICON="${COLOR_PURPLE}ℹ${RESET_COLOR}"
export SUCCESS_ICON="${COLOR_GREEN}✔${RESET_COLOR}"
export UPDATE_ICON="${COLOR_BLUE}↻${RESET_COLOR}"
export WARNING_ICON="${COLOR_YELLOW}⚠${RESET_COLOR}"
export LOADING_ICON="${COLOR_YELLOW}⏳${RESET_COLOR}"
