#!/bin/bash

#-------------------------------------------------------------
# Take a screenshot every n seconds
#-------------------------------------------------------------
function creep() {
    local -r seconds_to_wait="${1:-15}"

    while :; do
        echo "📸" "$(date +%H:%M:%S)"
        screencapture -x ~/Screenshots/"$(date +%s)".png
        sleep "${seconds_to_wait}"
    done
}
