#!/bin/zsh

#-------------------------------------------------------------
# Create a directory and cd into it
#
# Example: mcd <directory>
#-------------------------------------------------------------
function mcd() {
  mkdir -p "$1" && cd "$1"
}