#!/usr/bin/env zsh
# -----------------------------------------------------------------------
# This script is a simple HTTP server that serves files from the
# current directory. It uses Python's SimpleHTTPServer module to
# serve files over HTTP. It also opens the default web browser
# to the server's URL.
#
# Usage:
#   server [port]
#
# Examples:
#   server         # starts server on default port 8000
#   server 3000    # starts server on port 3000
#
# If no port is specified, it defaults to 8000.
# The script sets the Content-Type to `text/plain` for all files,
# and serves them as UTF-8. The script is designed to be run in
# a Unix-like environment.
# -----------------------------------------------------------------------
function server() {
  local port="${1:-8000}"

  sleep 1 && open "http://localhost:${port}/" &
  python3 -m http.server "$port"
}
