#!/bin/bash

# --------------------------------------------------------------------
# This function checks if a branch exists on the remote repository.
# It takes the branch name as an argument and checks if it exists
# on the remote repository. If the branch exists, it returns 1,
# otherwise it returns 0. If no branch name is provided, it prints
# an error message.
#
# Example:
#   gbc $(git_current_branch)
# --------------------------------------------------------------------
function gbc() {
  local -r branch_name="${1:-$(git_current_branch)}"

  if [[ -n "${branch_name}" ]]; then
    local -r exist_on_remote=$(git ls-remote --heads origin "${branch_name}")

    if [[ -z ${exist_on_remote} ]]; then
      echo 0
    else
      echo 1
    fi
  else
    echo "${fg[red]}Error:${reset_color} Branch name needed!"
  fi
}
