#!/bin/bash

# --------------------------------------------------------------------
# This function deletes a local branch in Git if it does not
# exist on the remote. It checks out the main branch, pulls
# the latest changes, prunes remote branches, deletes merged
# branches (except main and dev), and performs garbage
# collection.
#
# Example:
#   gbleach
# --------------------------------------------------------------------
function gbleach() {
  git checkout main &&
    git pull &&
    git remote prune origin &&
    git branch --merged |
    grep -vE "(^\*|main|dev)" |
      xargs git branch -d
}
