#!/bin/bash

# -------------------------------------------------------------------
# Outputs the name of the current branch
#
# Examples:
#   git pull origin $(git_current_branch)
#   git push origin $(git_current_branch)
#   git checkout -b new_branch $(git_current_branch)
#
# Using '--quiet' with 'symbolic-ref' will not cause a fatal error (128)
# if it's not a symbolic ref, but in a Git repo.
# --------------------------------------------------------------------
function git_current_branch() {
  local ref
  ref=$(git symbolic-ref --quiet HEAD 2>/dev/null)
  local ret=$?
  if [[ $ret != 0 ]]; then
    [[ $ret == 128 ]] && return # no git repo.
    ref=$(git rev-parse --short HEAD 2>/dev/null) || return
  fi
  echo "${ref#refs/heads/}"
}
